name: Publish Spin App
on:    
  workflow_dispatch:
    inputs: {}
  push: 
    branches:
    - main

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dagger
        shell: bash
        env:
          DAGGER_VERSION: "v0.14.0"
        run: |
          echo "::group::Installing dagger"
          curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=/usr/local/bin/ sudo -E sh
          echo "::endgroup::"

      - name: Publish tests-dashboard spin app
        run: |
          dagger -m github.com/rajatjindal/daggerverse/wasi@spin-push \
            call --docker-cfg=file:"$HOME/.docker/config.json" \
            registry-push --source=. --oci-artifact-name ghcr.io/rajatjindal/tests-dashboard-oci:$GITHUB_SHA --args "--build"
